version: '3.1'
services:
  config_service:
    container_name: config_service
    build: ./config-service
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: 'https://github.com/jandebora/spring-boot-git-config'
    ports:
      - 8888:8080
  db:
    container_name: mysql
    image: mysql:8
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - 10000:8080