version: '3.1'
services:
  config-service:
    container_name: config-service
    build: ./config-service
    image: jandebora/config-service:2.1.3
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: 'https://github.com/jandebora/spring-boot-git-config'
    ports:
      - 8080
  eureka-admin-service:
    container_name: eureka-admin-service
    build: ./registration-and-discovery-service
    image: jandebora/eureka-admin-service:2.1.3
    ports:
      - 8761:8761
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    image: jandebora/api-gateway:0.0.1
    environment:
      SPRING_CLOUD_CONFIG_ENABLED: 'true'
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_PROFILES_ACTIVE: master
      SPRING_CLOUD_CONFIG_LABEL: master
      SPRING_CLOUD_CONFIG_FAIL-FAST: 'true'
      SPRING_CLOUD_CONFIG_URI: 'http://config-service:8080'
    depends_on:
      - config-service
      - eureka-admin-service
    ports:
      - 80:8080
  users:
    container_name: users
    build: ./users-microservice
    image: jandebora/users-microservice:0.0.1
    environment:
      SPRING_CLOUD_CONFIG_ENABLED: 'true'
      SPRING_APPLICATION_NAME: users
      SPRING_PROFILES_ACTIVE: master
      SPRING_CLOUD_CONFIG_LABEL: master
      SPRING_CLOUD_CONFIG_FAIL-FAST: 'true'
      SPRING_CLOUD_CONFIG_URI: 'http://config-service:8080'
    depends_on:
      - config-service
      - db
      - eureka-admin-service
    ports:
      - 8080
  cards:
    container_name: cards
    build: ./cards-microservice
    image: jandebora/cards-microservice:0.0.1
    environment:
      SPRING_CLOUD_CONFIG_ENABLED: 'true'
      SPRING_APPLICATION_NAME: cards
      SPRING_PROFILES_ACTIVE: master
      SPRING_CLOUD_CONFIG_LABEL: master
      SPRING_CLOUD_CONFIG_FAIL-FAST: 'true'
      SPRING_CLOUD_CONFIG_URI: 'http://config-service:8080'
    depends_on:
      - config-service
      - db
      - eureka-admin-service
    ports:
      - 8080
  db:
    container_name: mysql
    image: mysql:8
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - 10000:8080