zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    cliente:
      path: /users/**
      serviceId: users
      stripPrefix: false
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
