spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cards
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create

server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
swagger:
  api-version: 1.0
  title: Card API
  description: Documentation Card API v${swagger.api-version}

springfox:
  documentation:
    swagger:
      v2:
        path: /cards/v2/api-docs
        