spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create

server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
management:
  endpoints:
    web:
      exposure:
        include: '*'