spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create

server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  api-version: 1.0
  title: User API
  description: Documentation User API v${swagger.api-version}
  
springfox:
  documentation:
    swagger:
      v2:
        path: /users/v2/api-docs